[package]
name = "pid"
version = "0.1.0"
authors = ["vincent <vincent.leporcher@telecom-paris.fr>"]
edition = "2018"

[dependencies]
dsp = { path = "../dsp" }
nalgebra = "0.23"

[dev-dependencies]
assert_approx_eq = "1.1.0"